// <auto-generated />
using Graduation.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Graduation.Core.Sqlite.Migrations.PostalCode
{
    [DbContext(typeof(PostalCodeContext))]
    [Migration("20210528180841_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Graduation.Core.PostalCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefecture")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("geo_PostalCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
